import type { Metadata } from "next";
import { Work_Sans, DM_Mono } from "next/font/google";
import "./globals.css";
import { SearchProvider } from "@/contexts/SearchContext";
import { Toaster } from "@/components/ui/sonner";

const workSans = Work_Sans({
    variable: "--font-work-sans",
    subsets: ["latin"],
});

const dmMono = DM_Mono({
    variable: "--font-dm-mono",
    subsets: ["latin"],
    weight: "400",
});

export const metadata: Metadata = {
    title: "Zem Studio",
    
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${workSans.variable} ${dmMono.variable} antialiased`}>
                <SearchProvider>{children}</SearchProvider>
                <Toaster
                    toastOptions={{
                        classNames: {
                            default: "!rounded-none !font-mono",
                        },
                    }}
                />
            </body>
        </html>
    );
}
