import type { Metadata } from "next";
import { Geist_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { SearchProvider } from "@/contexts/SearchContext";
import { Toaster } from "@/components/ui/sonner";

const spaceGrotesk = Space_Grotesk({
    variable: "--font-sans",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    display: "swap",
});

const geistMono = Geist_Mono({
    variable: "--font-display",
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Zem Studio",
    
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${spaceGrotesk.variable} ${geistMono.variable} antialiased`}>
                <SearchProvider>{children}</SearchProvider>
                <Toaster
                    toastOptions={{
                        classNames: {
                            default: "!rounded-none !font-mono",
                        },
                    }}
                />
            </body>
        </html>
    );
}
